default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] || Rails.application.credentials.database_database %>
  username: <%= ENV['DATABASE_USERNAME'] || Rails.application.credentials.database_username %>  
  password: <%= ENV['DATABASE_PASSWORD'] || Rails.application.credentials.database_password %>  
  host: <%= ENV['DATABASE_HOST'] || Rails.application.credentials.database_host %>  
  port: <%= ENV['DATABASE_PORT'] || Rails.application.credentials.database_port || '5432' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: personal_portfolio_app_development

test:
  <<: *default
  database: personal_portfolio_app_test

production:
  <<: *default
